name: Porject CI with Gradle

on: 
push:
branches: '*'
pull_request:
branches: '*'

jobs:
build:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@2
- name: Set up JDK 1.8
uses: actions/setup-java@1
with:
        java-version: 1.8
- name: Grant executive permission for gradlew
run: chmod +x gradlew
- name: Build with Gradle
run: ./gradlew build --info
